name: 'Trigger Workflows'
description: 'Trigger Worflows from Another Github Worflows'
author: 'Rocketium'
inputs:
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The name of the repository'
    required: true
  branch_name:
    description: 'The name of the branch'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true
  workflow_name:
    description: 'THe name of workflow file to trigger'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'fast-forward'
  color: 'green'
